const TnDistrictData = {
  Ariyalur: ["Andimadam", "Ariyalur", "Sendurai", "Udayarpalayam"],

  Chengalpattu: [
    "Chengalpattu",
    "Cheyyur",
    "Maduranthakam",
    "Pallavaram",
    "Tambaram",
    "Tirukalukundram",
    "Tiruporur",
    "Vandalur",
  ],

  Chennai: [
    "Alandur",
    "Ambattur",
    "Aminjikarai",
    "Ayanavaram",
    "Egmore",
    "Guindy",
    "Kolathur",
    "Maduravoyal",
    "Mambalam",
    "Mathavaram",
    "Mylapore",
    "Perambur",
    "Purasawalkam",
    "Sholinganallur",
    "Tiruvottiyur",
    "Tondiarpet",
    "Velachery",
  ],

  Coimbatore: [
    "Anaimalai",
    "Annur",
    "Coimbatore North",
    "Coimbatore South",
    "Kinathukadavu",
    "Madukkari",
    "Mettupalayam",
    "Perur",
    "Pollachi",
    "Sulur",
    "Valparai",
  ],

  Cuddalore: [
    "Bhuvanagiri",
    "Chidambaram",
    "Cuddalore",
    "Kattumannarkoil",
    "Kurinjipadi",
    "Panruti",
    "Srimushnam",
    "Tittakudi",
    "Veppur",
    "Virudhachalam",
  ],

  Dharmapuri: [
    "Dharmapuri",
    "Harur",
    "Karimangalam",
    "Nallampalli",
    "Palakkodu",
    "Pappireddipatti",
    "Pennagaram",
  ],

  Dindigul: [
    "Athoor",
    "Dindigul East",
    "Dindigul West",
    "Gujiliamparai",
    "Kodaikanal",
    "Natham",
    "Nilakkottai",
    "Oddanchatram",
    "Palani",
    "Vedasandur",
  ],

  Erode: [
    "Anthiyur",
    "Bhavani",
    "Erode",
    "Gobichettipalayam",
    "Kodumudi",
    "Modakkurichi",
    "Nambiyur",
    "Perundurai",
    "Sathyamangalam",
    "Thalavadi",
  ],

  Kallakurichi: [
    "Chinnasalem",
    "Kallakkurichi",
    "Kalvarayan Hills",
    "Sankarapuram",
    "Tirukkoyilur",
    "Ulundurpettai",
    "Vanapuram",
  ],

  Kancheepuram: [
    "Kancheepuram",
    "Kundrathur",
    "Sriperumbudur",
    "Uthiramerur",
    "Walajabad",
  ],

  Kanniyakumari: [
    "Agastheeswaram",
    "Kalkulam",
    "Killiyoor",
    "Thiruvattar",
    "Thovala",
    "Vilavancode",
  ],

  Karur: [
    "Aravakurichi",
    "Kadavur",
    "Karur",
    "Krishnarayapuram",
    "Kulithalai",
    "Manmangalam",
    "Pugalur",
  ],

  Krishnagiri: [
    "Anchetty",
    "Bargur",
    "Denkanikottai",
    "Hosur",
    "Krishnagiri",
    "Pochampalli",
    "Shoolagiri",
    "Uthangarai",
  ],

  Madurai: [
    "Kalligudi",
    "Madurai East",
    "Madurai North",
    "Madurai South",
    "Madurai West",
    "Melur",
    "Peraiyur",
    "Thirumangalam",
    "Thirupparankundram",
    "Usilampatti",
    "Vadipatti",
  ],

  Mayiladuthurai: ["Kuthalam", "Mayiladuthurai", "Sirkali", "Tharangambadi"],

  Nagapattinam: ["Kilvelur", "Nagapattinam", "Thirukkuvalai", "Vedaranyam"],

  Namakkal: [
    "Kolli Hills",
    "Kumarapalayam",
    "Mohanur",
    "Namakkal",
    "Paramathi Velur",
    "Rasipuram",
    "Sendamangalam",
    "Tiruchengode",
  ],

  Nilgiris: [
    "Coonoor",
    "Gudalur",
    "Kotagiri",
    "Kundah",
    "Panthalur",
    "Udhagamandalam",
  ],

  Perambalur: ["Alathur", "Kunnam", "Perambalur", "Veppanthattai"],

  Pudukkottai: [
    "Alangudi",
    "Aranthangi",
    "Avudayarkoil",
    "Gandarvakkottai",
    "Iluppur",
    "Karambakudi",
    "Kulathur",
    "Manamelkudi",
    "Ponnamaravathi",
    "Pudukkottai",
    "Thirumayam",
    "Viralimalai",
  ],

  Ramanathapuram: [
    "Kadaladi",
    "Kamuthi",
    "Kilakarai",
    "Mudukulathur",
    "Paramakudi",
    "Rajasingamangalam",
    "Ramanathapuram",
    "Rameswaram",
    "Tiruvadanai",
  ],

  Ranipet: ["Arakonam", "Arcot", "Kalavai", "Nemili", "Sholinghur", "Wallajah"],

  Salem: [
    "Attur",
    "Edappadi",
    "Gangavalli",
    "Kadayampatti",
    "Mettur",
    "Omalur",
    "Pethanaickanpalayam",
    "Salem",
    "Salem South",
    "Salem West",
    "Sankari",
    "Thalaivasal",
    "Vazhapadi",
    "Yercaud",
  ],

  Sivaganga: [
    "Devakottai",
    "Ilayangudi",
    "Kalaiyarkoil",
    "Karaikkudi",
    "Manamadurai",
    "Singampunari",
    "Sivaganga",
    "Thiruppathur",
    "Thiruppuvanam",
  ],

  Tenkasi: [
    "Alangulam",
    "Kadayanallur",
    "Sankarankoil",
    "Shenkottai",
    "Sivagiri",
    "Tenkasi",
    "Tiruvengadam",
    "Veerakeralamputhur",
  ],

  Thanjavur: [
    "Budalur",
    "Kumbakonam",
    "Orathanadu",
    "Papanasam",
    "Pattukkottai",
    "Peravurani",
    "Thanjavur",
    "Thiruvaiyaru",
    "Thiruvidaimarudur",
    "Thiruvonam",
  ],

  Theni: [
    "Andipatti",
    "Bodinayakanur",
    "Periyakulam",
    "Theni",
    "Uthamapalayam",
  ],

  Thiruvallur: [
    "Avadi",
    "Gummidipoondi",
    "Pallipattu",
    "Ponneri",
    "Poonamallee",
    "R K Pet",
    "Thiruvallur",
    "Tiruttani",
    "Uthukkottai",
  ],

  Thiruvarur: [
    "Koothanallur",
    "Kudavasal",
    "Mannargudi",
    "Muthupettai",
    "Nannilam",
    "Needamangalam",
    "Thiruthuraipoondi",
    "Thiruvarur",
    "Valangaiman",
  ],

  Thoothukkudi: [
    "Eral",
    "Ettayapuram",
    "Kayathar",
    "Kovilpatti",
    "Ottapidaram",
    "Sathankulam",
    "Srivaikuntam",
    "Thoothukkudi",
    "Tiruchendur",
    "Vilathikulam",
  ],

  Tiruchirappalli: [
    "Lalgudi",
    "Manachanallur",
    "Manapparai",
    "Marungapuri",
    "Musiri",
    "Srirangam",
    "Thiruverumbur",
    "Thottiyam",
    "Thuraiyur",
    "Tiruchirappalli East",
    "Tiruchirappalli West",
  ],

  Tirunelveli: [
    "Ambasamudram",
    "Cheranmahadevi",
    "Manur",
    "Nanguneri",
    "Palayamkottai",
    "Radhapuram",
    "Tirunelveli",
    "Tisayanvilai",
  ],

  Tirupathur: ["Ambur", "Natrampalli", "Tirupathur", "Vaniyambadi"],

  Tiruppur: [
    "Avinashi",
    "Dharapuram",
    "Kangeyam",
    "Madathukulam",
    "Palladam",
    "Tiruppur North",
    "Tiruppur South",
    "Udumalaipettai",
    "Uthukuli",
  ],

  Tiruvannamalai: [
    "Arani",
    "Chengam",
    "Chetpet",
    "Cheyyar",
    "Jamunamarathoor",
    "Kalasapakkam",
    "Kilpennathur",
    "Polur",
    "Thandrampet",
    "Tiruvannamalai",
    "Vandavasi",
    "Vembakkam",
  ],

  Vellore: ["Anaicut", "Gudiyatham", "K V Kuppam", "Katpadi", "Pernambut", "Vellore"],

  Viluppuram: [
    "Gingee",
    "Kandachipuram",
    "Marakanam",
    "Melmalaiyanur",
    "Thiruvennainallur",
    "Tindivanam",
    "Vanur",
    "Vikravandi",
    "Viluppuram",
  ],

  Virudhunagar: [
    "Aruppukkottai",
    "Kariapatti",
    "Rajapalayam",
    "Sattur",
    "Sivakasi",
    "Srivilliputhur",
    "Tiruchuli",
    "Vembakottai",
    "Virudhunagar",
    "Watrap",
  ],
  Pondicherry: [

    "Ozhukarai (Oulgaret)",
    "Puducherry",
    "Villianur ",
       "Bahour",
  ],
};

export default TnDistrictData;