const courseData = {
  1: {
    title: "SEMP – Smartphone Entrepreneurship Management Program",
    year: "2025",
    fee: "₹75,000 (Original: ₹1,00,000)",
    duration:
      "25 Days Campus Training + 1 Year Online Support (Zoom + WhatsApp)",
    mode: "Residential Program – Accommodation, Food & Refreshments Included",

    highlight: [
      "Toolkit & Joining Kit (T-Shirt, Notebook, ID Card, Tools, Certificate)",
      "Business Loan Support: ₹3 Lakhs – ₹50 Lakhs",
      "Limited Seats | Venue: Radnus Training Campus, Pondicherry",
    ],

    learn: [
      "Smartphone Repair – Basics to Chip-Level (IC, eMMC, UFS, 120+ Case Studies)",
      "Digital Marketing – Google Business, WhatsApp & Meta Ads, SEO, Reels",
      "Business Setup – 5-Department Store Model (Recharge, DTP, Services, Accessories, Refurbished)",
      "Business Automation – Service Apps, CRM, Inventory & Billing Software",
      "Accounts – GST, Cashflow, Pricing, Loan Planning up to ₹50 Lakhs",
      "People Management – Hiring, Salary System, Staff Supervision & Retention",
    ],

    whoCanJoin: [
      "Mobile Shop Owners & Business Starters",
      "ITI, Diploma, Engineering & Degree Holders",
      "Job Seekers & Housewives",
    ],

    why: "SEMP is more than training – it is a launchpad to become a Mobile Shop Owner in your Taluk. Earn ₹5,000/day with proven tools, techniques and Radnus support.",
  },

  2: {
    title: "LEMP – Laptop Entrepreneurship / Engineering Management Program",
    fee: "₹45,000",
    duration: "3–6 Months",
    mode: "Hands-on Practical + Business Coaching",
    details: [
      "Laptop Motherboard Diagnosis & Repair",
      "OS Installation, Formatting & Virus Removal",
      "Software Troubleshooting & Driver Management",
      "Power Supply, Battery & Charging Circuit Fixes",
      "Business Modules – Shop Setup, Inventory, Pricing & Customer Care",
      "Profit Strategies – Run Laptop & Mobile Business Together",
      "Toolkit + Radnus Student Kit Free",
      "1 Year Online Support (Zoom + WhatsApp)",
      "Residential Package Available – Stay + Food + Refreshments",
    ],
    whoCanJoin: [
      "Mobile Technicians expanding into Laptop Services",
      "Students & Job Seekers in IT Hardware",
      "Entrepreneurs starting Multi-Service Tech Centers",
    ],
    why: "LEMP transforms you into a Laptop Service Professional + Entrepreneur. Grow beyond mobiles and open a multi-brand service hub in your city.",
  },
  3: {
    title: "STEP – Smartphone Technical Education Program",
    fee: "₹35,000",
    duration: "1–3 Months",
    details: [
      "Mobile Hardware Repair – IC, Connectors, Display, Battery Issues",
      "Software Flashing & Unlocking – Android + iOS Basics",
      "Troubleshooting – Step-by-step Diagnosis Methods",
      "Hands-On Training: Hardware + Software + IC Replacement",
      "Real-Time Practice with 50+ Live Case Studies",
      "Billing & Customer Care – Service Center Workflow",
      "Career Guidance – Start Your Own Shop or Work in Top Labs",
      "Residential Option: Hostel + Food + Refreshments",
      "Professional Toolkit + Radnus Kit Included",
      "1 Year Online Support – Zoom + WhatsApp Doubt Sessions",
    ],
    whoCanJoin: [
      "10th / 12th Students",
      "College Dropouts",
      "Job Seekers entering the Mobile Service Industry",
      "Entrepreneurs planning to start a Mobile Repair Shop",
    ],
    why: "STEP gives you job-ready skills in just 90 days. Learn, practice, and start earning immediately in your town.",
  },
  4: {
    title: "AEMP – Advanced eMMC / UFS Chip-Level Program",
    fee: "₹45,000",
    duration: "30 Days Intensive Training",
    details: [
      "eMMC / UFS / NAND Chip Programming",
      "Data Recovery from Dead Phones",
      "IC Reballing & Replacement",
      "BGA Rework & Advanced Soldering Techniques",
      "Real-Time Case Studies on Flagship Smartphones",
      "High-Value Repair Jobs – Boost Your Earnings",
      "Chip-Level Expertise: Advanced IC & Memory Repair",
      "Lab Access: BGA Rework Stations, Microscopes, Programmers",
      "30 Days Full Practical Training + 1 Year Zoom & WhatsApp Support",
      "Radnus Advanced Kit Included",
      "Professional Certification Recognized by Leading Service Centers",
    ],
    whoCanJoin: [
      "Experienced Mobile Technicians",
      "SEMP & STEP Alumni",
      "Service Center Professionals upgrading their Chip-Level Skills",
    ],
    why: "AEMP makes you an advanced specialist in chip-level repairs. Do the jobs others reject and earn premium income in the market.",
  },
  5: {
    title: "1-Day Basic Mobile Service Training Program",
    fee: "₹7,500",
    duration: "1 Day (10:00 AM – 5:30 PM)",
    details: [
      "Tools & Equipment Handling: Blower (Hot Air Gun), DC Power Supply, Digital Multimeter",
      "Assembling & Disassembling – Understanding smartphone components",
      "Charging Connector (CC Pin) Replacement – Desoldering, Soldering, Fixing Connectors",
      "Display Changing – Safe removal & replacement techniques",
      "Hands-On Practical on 2 Devices: 1 Jio Keypad Phone + 1 Android Smartphone",
      "Starter Tool Kit Worth ₹500 Included",
      "Certificate of Completion – Radnus Certified Basic Technician",
      "Radnus Alumni Access for Continuous Support",
      "Food, Refreshments & Snacks Provided During the Program",
    ],
    whoCanJoin: [
      "Beginners who want to enter mobile repair",
      "Students exploring technical skills",
      "Part-time learners and hobbyists",
      "Small shop owners wanting to add basic services",
      "Anyone interested in learning mobile repair fundamentals in 1 day",
    ],
    why: "A single-day live practical workshop to spark your mobile repair career with real devices, tools, and guided hands-on training.",
  },
  6: {
    title: "Advanced Flashing & Unlocking (2 Days)",
    fee: "₹22,000",
    duration: "2 Days (10:00 AM – 5:30 PM)",
    details: [
      "Install, Configure & Use 15+ Flashing Tools",
      "FRP Unlocking, Pattern Unlock & Network Unlock for Multi-Brands",
      "IMEI Repair & Restoration Techniques",
      "Flash Stock ROMs & Custom ROMs",
      "Recover Bootloop, Dead Devices & Software-Corrupted Phones",
      "Advanced Unlocking & Servicing with UMT Pro & Chimera Tools",
      "Multi-Brand Flashing Tools Covered: ASUS, MI, MOTO, Samsung, Sony, Mediatek, Spectrum, Qualcomm",

      "Certification: Radnus Certified Android Flashing & Unlocking Technician",
      "Accommodation, Food, Refreshments & Snacks Included",
      "Radnus Alumni Membership for Long-Term Support",
    ],
    whoCanJoin: [
      "Mobile Technicians who want to upgrade software skills",
      "Service Center Professionals handling flashing & unlocking jobs",
      "Repair Shop Owners offering FRP/IMEI/Unlocking services",

      "Anyone interested in advanced Android software troubleshooting",
    ],
    why: "Become an expert in Android flashing, unlocking, IMEI repair, and multi-brand software solutions with hands-on advanced training.",
  },
  7: {
    title: "Microscope & Micro-Components Replacement Program",
    fee: "₹10,000",
    duration: "1 Day (10:00 AM – 5:30 PM)",
    details: [
      "Microscope Handling & Management – Positioning, Magnification & Focus Control",
      "Hand–Eye Coordination Techniques for Precision Micro-Work",
      "Maintenance & Cleaning for Clear Visibility",
      "SMD Component Identification – Resistors, Capacitors, IC Pins",
      "Safe Removal & Re-Soldering with Hot Air Station + Soldering Iron",
      "Micro-Jumpers Installation using Ultra-Thin Wires under Microscope",
      "Best Practices to Avoid Shorts & Ensure Strong, Durable Joints",
      "Certificate of Completion – Radnus Certified Micro-Soldering Technician",
      "Food, Refreshments & Snacks Included",
      "Radnus Alumni Access for Ongoing Guidance & Support",
    ],
    whoCanJoin: [
      "Mobile Technicians upgrading to micro-level soldering",
      "Service Center Professionals handling motherboard-level repairs",
      "Technicians who want to improve microscope soldering accuracy",
      "Students from STEP/SEMP seeking advanced hands-on training",
      "Any repair enthusiast wanting to master precision micro-soldering",
    ],
    why: "Precision-driven training designed to upgrade your skills to micro-level repair expertise.",
  },
  8: {
    title: "UMT Pro – Half-Day Technical Training",
    fee: "₹5,000",
    duration: "Half Day (10:00 AM – 1:30 PM)",
    details: [
      "UMT Pro Dongle Setup – Installation, Drivers & Interface Overview",
      "IMEI Repair & Flashing – Step-by-Step Procedure for Supported Models",
      "FRP Unlocking for Samsung, Xiaomi & Other Android Devices",
      "Pattern / PIN / Password Reset (Without Data Loss Where Possible)",
      "Software Update & Recovery – Fixing Bootloops & Dead Software Issues",
      "Backup & Restore Functions to Safeguard User Data",
      "Certification – Radnus Certified UMT Pro Technician",
      "Lunch, Refreshments & Snacks Included",
      "Radnus Alumni Access for Post-Training Support",
    ],
    whoCanJoin: [
      "Mobile Technicians wanting to master UMT Pro quickly",
      "Service Center Professionals handling flashing & unlocking tasks",
      "Technicians upgrading software repair skills",
      "Repair Shop Owners offering FRP / IMEI / Reset services",
      "Beginners from STEP or other programs wanting tool-based training",
    ],
    why: "A fast, power-packed live practical session to unlock the full potential of UMT Pro for real-world software repairs.",
  },
  9: {
    title: "OCA Lamination & Glass Changing Workshop",
    fee: "₹5,999",
    duration: "Half Day (10:00 AM – 1:30 PM & 2:30 PM – 4:00 PM)",
    details: [
      "OCA Machine Setup, Safety & Handling",
      "Touch Separator Usage for Safe Glass Removal",
      "Bubble Remover (Autoclave) Operation",
      "Flat & Curved Screen Lamination Workflow",
      "Quality Control, Cleaning & Final Testing Procedures",
      "SOP PDFs Included – Cleaning, Lamination, Autoclave & QC Checklist",
      "Price Matrix Template for Job Costing & Warranty Planning",
      "Post-Training 7-Day WhatsApp Support for Basic Doubts",
      "Completion Certificate (Same Day)",
      "1 Trainee : 1 Workstation Hands-On Practical Training",
      "Lunch, Refreshments & Snacks Included",
    ],
    whoCanJoin: [
      "Mobile Shop Owners & Technicians upgrading to in-house glass replacement",
      "Service Entrepreneurs planning to start a glass refurbishing line",
      "Fresher Technicians who want to learn high-demand OCA & glass-changing skills",

      "Anyone interested in mastering OCA lamination and autoclave workflows",
    ],
    why: "Learn one of the most profitable and in-demand services in mobile repair with hands-on OCA lamination and glass refurbishing techniques.",
  },
  10: {
    title: "Tempered Glass Cutting – Fast Track Program",
    fee: "₹2,999",
    duration: "3 Hours (10:00 AM – 1:00 PM)",
    details: [
      "Automatic Machine Setup – Power Connections, Blade Calibration & Safety Guidelines",
      "Glass Thickness Selection for Different Mobile & Tablet Models",
      "Step-by-Step Tempered Glass Cutting for Flat & Curved Models",
      "Live Practical Demo on Multiple Glass Types (Mobile, Edge, Tablet)",
      "Troubleshooting & Quality Control – Avoiding Cracks, Scratches & Wastage",
      "Business Insights – Costing Per Glass, Daily Output & Profit Calculation",
      "Certificate of Completion – Radnus Certified Tempered Glass Cutting Operator",
      "Lunch, Refreshments & Snacks Included",
      "Radnus Alumni Access for Future Support",
    ],
    whoCanJoin: [
      "Mobile Shop Owners wanting to add in-house tempered glass cutting",

      "Entrepreneurs starting a small-scale tempered glass business",
      "Beginners who want to learn machine-based precision cutting",
      "Repair professionals seeking a profitable add-on skill",
    ],
    why: "A quick skill-based, high-demand practical program ideal for shop owners and technicians looking to add profitable tempered glass cutting services.",
  },
};

export default courseData;
